<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
function patch_snapshot():array{
 $d=db();$one=static function(mysqli $d,string $q):int{$r=$d->query($q);if(!$r)throw new RuntimeException('Falha na análise do banco.');return(int)$r->fetch_row()[0];};
 $macInsert=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND TRIGGER_NAME='mkauth_preserva_case_mac_insert'");
 $macUpdate=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND TRIGGER_NAME='mkauth_preserva_case_mac_update'");
 $conflicts=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND EVENT_OBJECT_TABLE='sis_cliente' AND TRIGGER_NAME IN ('sis_cliente_lowercase_mac','sis_cliente_mac_lower_insert','sis_cliente_mac_lower_update')");
 $total=$one($d,"SELECT COUNT(*) FROM sis_plano");$input=$one($d,"SELECT COUNT(DISTINCT groupname) FROM radgroupreply WHERE attribute='Huawei-Input-Average-Rate'");$output=$one($d,"SELECT COUNT(DISTINCT groupname) FROM radgroupreply WHERE attribute='Huawei-Output-Average-Rate'");
 $mismatch=$one($d,"SELECT COUNT(*) FROM sis_plano p LEFT JOIN radgroupreply i ON i.groupname=p.nome AND i.attribute='Huawei-Input-Average-Rate' LEFT JOIN radgroupreply o ON o.groupname=p.nome AND o.attribute='Huawei-Output-Average-Rate' WHERE i.groupname IS NULL OR o.groupname IS NULL OR i.op<>'=' OR o.op<>'=' OR CAST(i.value AS UNSIGNED)<>CAST(COALESCE(NULLIF(p.velup,''),'0') AS UNSIGNED)*1000 OR CAST(o.value AS UNSIGNED)<>CAST(COALESCE(NULLIF(p.veldown,''),'0') AS UNSIGNED)*1000");
 $d->query("CREATE TABLE IF NOT EXISTS addon_huawei_patch_jobs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,status VARCHAR(16) NOT NULL,requested_by VARCHAR(100) NOT NULL,requested_at DATETIME NOT NULL,finished_at DATETIME NULL,message TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$job=null;$r=$d->query("SELECT id,status,requested_by,requested_at,finished_at,message FROM addon_huawei_patch_jobs ORDER BY id DESC LIMIT 1");if($r&&$row=$r->fetch_assoc())$job=$row;$d->close();
 $cron=is_file('/etc/cron.d/mkauth-huawei-planos')&&str_contains((string)@file_get_contents('/etc/cron.d/mkauth-huawei-planos'),'/root/planos/att-planos-huawei.sh');$last=is_file('/var/log/mkauth-huawei-planos.log')?date('Y-m-d H:i:s',filemtime('/var/log/mkauth-huawei-planos.log')):'nunca';$macOk=$macInsert===1&&$macUpdate===1&&$conflicts===0;$plansOk=$mismatch===0&&$input===$total&&$output===$total;
 return['ok'=>true,'mac'=>['ok'=>$macOk,'insert'=>$macInsert,'update'=>$macUpdate,'conflicts'=>$conflicts],'plans'=>['ok'=>$plansOk,'total'=>$total,'input'=>$input,'output'=>$output,'mismatches'=>$mismatch],'automatic'=>['ok'=>$cron,'last_run'=>$last],'job'=>$job,'message'=>$macOk&&$plansOk&&$cron?'Patch de planos e MAC aplicado, validado e automático.':'Análise concluída. Existem itens pendentes ou ainda não ativados.'];
}
try{
 $action=$_SERVER['REQUEST_METHOD']==='POST'?(string)($_POST['action']??'status'):'status';if($action==='apply'){require_csrf((string)($_POST['csrf']??''));$d=db();$d->query("CREATE TABLE IF NOT EXISTS addon_huawei_patch_jobs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,status VARCHAR(16) NOT NULL,requested_by VARCHAR(100) NOT NULL,requested_at DATETIME NOT NULL,finished_at DATETIME NULL,message TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$pending=$d->query("SELECT COUNT(*) FROM addon_huawei_patch_jobs WHERE status IN ('pending','running')")->fetch_row()[0];if((int)$pending>0)throw new RuntimeException('Já existe uma aplicação aguardando ou em execução.');$user=(string)($_SESSION['MKA_Usuario']??$_SESSION['MM_Usuario']??'MK-AUTH');$st=$d->prepare("INSERT INTO addon_huawei_patch_jobs(status,requested_by,requested_at,message) VALUES('pending',?,NOW(),'Solicitação confirmada no addon')");$st->bind_param('s',$user);$st->execute();$st->close();$d->close();$result=patch_snapshot();$result['queued']=true;$result['message']='Aplicação autorizada e colocada na fila segura. O executor iniciará em até 1 minuto.';json_response($result);}
 if($action!=='status')throw new RuntimeException('Ação inválida.');json_response(patch_snapshot());
}catch(Throwable $e){json_response(['ok'=>false,'error'=>$e->getMessage()],422);}
