<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';require __DIR__.'/huawei_client.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['ok'=>false,'error'=>'Método não permitido.'],405);

function wizard_source_ip(string $target):string{$out=[];$code=1;exec('/sbin/ip route get '.escapeshellarg($target).' 2>/dev/null',$out,$code);$text=implode(' ',$out);return preg_match('/\bsrc\s+(\d+\.\d+\.\d+\.\d+)/',$text,$m)?$m[1]:'';}
function wizard_connection():array{$c=addon_config();$host=trim((string)($_POST['wizard_host']??''));$port=(int)($_POST['wizard_port']??22);$user=trim((string)($_POST['wizard_user']??''));$password=(string)($_POST['wizard_password']??'');if(!filter_var($host,FILTER_VALIDATE_IP))throw new RuntimeException('Informe o IP Huawei para esta análise.');if($port<1||$port>65535)throw new RuntimeException('Porta SSH temporária inválida.');if($user===''||strlen($user)>64||$password==='')throw new RuntimeException('Informe usuário e senha temporários do Huawei.');$c['ssh_host']=$host;$c['ssh_port']=$port;$c['ssh_user']=$user;$c['ssh_password']=$password;return$c;}
function wizard_values(array $c):array{$community=trim((string)($_POST['community']??''));if(strlen($community)<8||!preg_match('/[A-Za-z]/',$community)||!preg_match('/[0-9]/',$community))throw new RuntimeException('A community deve ter ao menos 8 caracteres, letras e números.');$target=(string)($c['snmp_host']??$c['nas_ip']??$c['ssh_host']);$source=wizard_source_ip($target);if(!filter_var($source,FILTER_VALIDATE_IP))throw new RuntimeException('Não foi possível identificar o IP de origem do MK-AUTH.');return[$community,$source];}
function wizard_addon_user():array{$user=trim((string)($_POST['addon_user']??''));$password=(string)($_POST['addon_password']??'');if(!preg_match('/^[A-Za-z][A-Za-z0-9_-]{5,31}$/',$user))throw new RuntimeException('Usuário dedicado inválido. Use de 6 a 32 letras, números, _ ou -.');if(strlen($password)<12||!preg_match('/[A-Z]/',$password)||!preg_match('/[a-z]/',$password)||!preg_match('/[0-9]/',$password))throw new RuntimeException('A senha dedicada deve ter ao menos 12 caracteres, maiúscula, minúscula e número.');return[$user,$password];}
function wizard_snmp_test(array $c):array{$host=(string)($c['snmp_host']??$c['nas_ip']??'');$community=(string)($c['snmp_community']??'');if($host===''||$community==='')return['ok'=>false,'message'=>'Community não informada ao addon; não foi possível executar o teste real.'];$out=[];$rc=1;$start=microtime(true);exec('/usr/bin/snmpget -v2c -c '.escapeshellarg($community).' -t 3 -r 1 '.escapeshellarg($host).' 1.3.6.1.2.1.1.3.0 2>&1',$out,$rc);$ms=(int)round((microtime(true)-$start)*1000);return['ok'=>$rc===0,'message'=>$rc===0?"Consulta SNMP v2c aprovada em {$ms} ms.":'A community configurada não respondeu ao teste SNMP.','latency_ms'=>$ms];}
function wizard_inventory(array $c):array{
    $target=(string)($c['snmp_host']??$c['nas_ip']??$c['ssh_host']);$source=wizard_source_ip($target);
    $out=huawei_exec($c,"display version\ndisplay snmp-agent community\ndisplay snmp-agent usm-user\ndisplay current-configuration | include snmp-agent\ndisplay acl all");
    $communities=[];$blocks=preg_split('/(?=\s*Community name:)/i',$out)?:[];
    foreach($blocks as $b){if(!preg_match('/Community name:\s*(\S+)/i',$b,$m))continue;$alias=preg_match('/Alias name:\s*(\S+)/i',$b,$a)?$a[1]:'sem alias';$acl=preg_match('/Acl:\s*(\d+)/i',$b,$x)?$x[1]:'';$communities[]=['alias'=>$alias,'acl'=>$acl,'encrypted'=>str_contains($m[1],'%^%#')];}
    preg_match_all('/Basic ACL\s+(\d+),.*?(?=\n\s*Basic ACL|\z)/is',$out,$aclBlocks,PREG_SET_ORDER);$acls=[];
    foreach($aclBlocks as $ab){$number=$ab[1];$permit=(bool)preg_match('/rule\s+\d+\s+permit\s+source\s+'.preg_quote($source,'/').'\s+0(?:\s|\()/i',$ab[0]);$matches=0;if(preg_match('/rule\s+\d+\s+permit\s+source\s+'.preg_quote($source,'/').'\s+0\s*\((\d+)\s+times matched\)/i',$ab[0],$mm))$matches=(int)$mm[1];$acls[$number]=['number'=>$number,'source_permitted'=>$permit,'matches'=>$matches];}
    $v3=[];if(preg_match_all('/(?:User name|UserName)\s*:\s*(\S+)/i',$out,$users))$v3=array_values(array_unique($users[1]));
    $snmp=wizard_snmp_test($c);$recommendations=[];
    foreach($communities as $community){$acl=$community['acl']?:'sem ACL';$recommendations[]="Community v2c encontrada: alias {$community['alias']}, ACL {$acl}; o nome real está cifrado e não pode ser exibido.";if(isset($acls[$community['acl']])){$a=$acls[$community['acl']];$recommendations[]=$a['source_permitted']?"ACL {$a['number']} APROVADA: permite {$source}/32 e registra {$a['matches']} correspondências.":"ACL {$a['number']} BLOQUEIA/NÃO LIBERA {$source}/32.";}}
    $recommendations[]=$v3?'Usuários SNMPv3 encontrados: '.implode(', ',$v3).'.':'Nenhum usuário SNMPv3 identificado; a consulta atual usa community v2c.';
    $recommendations[]='Teste real: '.$snmp['message'];
    if(!$communities)$recommendations[]='Nenhuma community SNMP v2c foi identificada; crie uma community somente leitura.';
    foreach($communities as $community){$acl=$community['acl'];if($acl===''||!isset($acls[$acl]))$recommendations[]="A community {$community['alias']} não possui uma ACL verificável.";elseif(!$acls[$acl]['source_permitted'])$recommendations[]="A ACL {$acl}, usada pela community {$community['alias']}, não permite o IP {$source}.";}
    if(!$snmp['ok'])$recommendations[]='Ação necessária: confirme a community salva no addon e a ACL associada.';if($snmp['ok']&&!array_filter($communities,fn($x)=>isset($acls[$x['acl']])&&!$acls[$x['acl']]['source_permitted']))$recommendations[]='Resultado final: SNMP liberado e funcionando para este MK-AUTH.';
    return['ok'=>true,'source_ip'=>$source,'snmp_configured'=>!empty($communities),'acl_detected'=>!empty($acls),'communities'=>$communities,'acls'=>array_values($acls),'snmp_v3_users'=>$v3,'snmp_test'=>$snmp,'recommendations'=>$recommendations,'message'=>'Análise concluída com inventário de communities, ACLs e teste real SNMP.'];
}

try{
 require_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');$c=wizard_connection();
 if($action==='inventory')json_response(wizard_inventory($c));
 [$community,$source]=wizard_values($c);[$addonUser,$addonPassword]=wizard_addon_user();$commands="system-view\nssh user $addonUser\naaa\n local-user $addonUser password irreversible-cipher $addonPassword\n local-user $addonUser service-type ssh\n local-user $addonUser level 3\n quit\nssh user $addonUser authentication-type password\nssh user $addonUser service-type stelnet\nacl number 2999\n rule 15 permit source $source 0\n quit\nsnmp-agent\nsnmp-agent sys-info version v2c\nsnmp-agent community read cipher $community acl 2999\ncommit\nreturn";
 if($action==='generate')json_response(['ok'=>true,'commands'=>$commands,'source_ip'=>$source,'message'=>'Configuração manual gerada.']);
 if($action!=='apply'||($_POST['confirm']??'')!=='APLICAR')throw new RuntimeException('Confirmação automática inválida.');$out=huawei_exec($c,$commands);if(preg_match('/Error:|Unrecognized command|Wrong parameter/i',$out))throw new RuntimeException('O Huawei recusou um comando. Use o modo manual e confira a versão do equipamento.');
 $saved=addon_config();$saved['snmp_community']=$community;$saved['ssh_host']=$c['ssh_host'];$saved['ssh_port']=$c['ssh_port'];$saved['ssh_user']=$addonUser;$saved['ssh_password']=$addonPassword;save_addon_config($saved);$test=wizard_snmp_test($saved);json_response(['ok'=>$test['ok'],'commands'=>$commands,'source_ip'=>$source,'message'=>$test['ok']?'Configuração aplicada e SNMP validado.':'Comandos aplicados, mas o teste SNMP ainda não respondeu.','test_output'=>$test['message']]);
}catch(Throwable $e){json_response(['ok'=>false,'error'=>$e->getMessage()],422);}
