<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
function patch_snapshot():array{
 $d=db();$one=static function(mysqli $d,string $q):int{$r=$d->query($q);if(!$r)throw new RuntimeException('Falha na análise do banco.');return(int)$r->fetch_row()[0];};
 $macInsert=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND TRIGGER_NAME='mkauth_preserva_case_mac_insert'");$macUpdate=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND TRIGGER_NAME='mkauth_preserva_case_mac_update'");$conflicts=$one($d,"SELECT COUNT(*) FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND EVENT_OBJECT_TABLE='sis_cliente' AND TRIGGER_NAME IN ('sis_cliente_lowercase_mac','sis_cliente_mac_lower_insert','sis_cliente_mac_lower_update')");
 $triggerNames=[];$r=$d->query("SELECT TRIGGER_NAME FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA='mkradius' AND EVENT_OBJECT_TABLE='sis_cliente' ORDER BY TRIGGER_NAME");while($r&&$x=$r->fetch_row())$triggerNames[]=$x[0];
 $total=$one($d,"SELECT COUNT(*) FROM sis_plano");$input=$one($d,"SELECT COUNT(DISTINCT p.nome) FROM sis_plano p JOIN radgroupreply r ON r.groupname=p.nome WHERE r.attribute='Huawei-Input-Average-Rate'");$output=$one($d,"SELECT COUNT(DISTINCT p.nome) FROM sis_plano p JOIN radgroupreply r ON r.groupname=p.nome WHERE r.attribute='Huawei-Output-Average-Rate'");$orphans=$one($d,"SELECT COUNT(*) FROM radgroupreply r LEFT JOIN sis_plano p ON p.nome=r.groupname WHERE r.attribute IN ('Huawei-Input-Average-Rate','Huawei-Output-Average-Rate') AND (TRIM(r.groupname)='' OR p.nome IS NULL)");$where="i.groupname IS NULL OR o.groupname IS NULL OR i.op<>'=' OR o.op<>'=' OR CAST(i.value AS UNSIGNED)<>CAST(COALESCE(NULLIF(p.velup,''),'0') AS UNSIGNED)*1000 OR CAST(o.value AS UNSIGNED)<>CAST(COALESCE(NULLIF(p.veldown,''),'0') AS UNSIGNED)*1000";$mismatch=$one($d,"SELECT COUNT(*) FROM sis_plano p LEFT JOIN radgroupreply i ON i.groupname=p.nome AND i.attribute='Huawei-Input-Average-Rate' LEFT JOIN radgroupreply o ON o.groupname=p.nome AND o.attribute='Huawei-Output-Average-Rate' WHERE $where");$blockTotal=$one($d,"SELECT COUNT(DISTINCT username) FROM radreply WHERE attribute='Framed-Pool' AND value='pgcorte'");$blockReady=$one($d,"SELECT COUNT(*) FROM (SELECT p.username FROM radreply p JOIN radreply w ON w.username=p.username AND w.attribute='Framed-IPv6-Pool' AND w.value='bloqueiov6prefix' JOIN radreply x ON x.username=p.username AND x.attribute='Huawei-Delegated-IPv6-Prefix-Pool' AND x.value='pgcorte' WHERE p.attribute='Framed-Pool' AND p.value='pgcorte' GROUP BY p.username) ready");
 $pendingPlans=[];$r=$d->query("SELECT p.nome,p.velup,p.veldown,COALESCE(i.value,'AUSENTE') input_atual,COALESCE(o.value,'AUSENTE') output_atual FROM sis_plano p LEFT JOIN radgroupreply i ON i.groupname=p.nome AND i.attribute='Huawei-Input-Average-Rate' LEFT JOIN radgroupreply o ON o.groupname=p.nome AND o.attribute='Huawei-Output-Average-Rate' WHERE $where ORDER BY p.nome LIMIT 100");while($r&&$x=$r->fetch_assoc())$pendingPlans[]=$x;
 $d->query("CREATE TABLE IF NOT EXISTS addon_huawei_patch_jobs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,status VARCHAR(16) NOT NULL,requested_by VARCHAR(100) NOT NULL,requested_at DATETIME NOT NULL,finished_at DATETIME NULL,message TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$job=null;$r=$d->query("SELECT id,status,requested_by,requested_at,finished_at,message FROM addon_huawei_patch_jobs ORDER BY id DESC LIMIT 1");if($r&&$row=$r->fetch_assoc())$job=$row;$d->close();
 $cronText=(string)@file_get_contents('/etc/cron.d/mkauth-huawei-planos');$cronConfigured=strpos($cronText,'/root/planos/att-planos-huawei.sh')!==false;$heartbeat='/var/run/mkauth-huawei-planos.last';$last=is_file($heartbeat)?date('Y-m-d H:i:s',filemtime($heartbeat)):'sem confirmação';$recent=is_file($heartbeat)&&time()-filemtime($heartbeat)<=180;$log=(string)@file_get_contents('/var/log/mkauth-huawei-planos.log');$logTail=implode("\n",array_slice(preg_split('/\R/',$log)?:[],-20));$macOk=$macInsert===1&&$macUpdate===1&&$conflicts===0;$plansOk=$mismatch===0&&$input===$total&&$output===$total;$autoOk=$cronConfigured&&$recent;
 $plansOk=$plansOk&&$orphans===0;$blockOk=$blockReady===$blockTotal;return['ok'=>true,'mac'=>['ok'=>$macOk,'insert'=>$macInsert,'update'=>$macUpdate,'conflicts'=>$conflicts,'triggers'=>$triggerNames],'plans'=>['ok'=>$plansOk,'total'=>$total,'input'=>$input,'output'=>$output,'mismatches'=>$mismatch,'orphans'=>$orphans,'pending'=>$pendingPlans],'blocking'=>['ok'=>$blockOk,'total'=>$blockTotal,'ready'=>$blockReady],'automatic'=>['ok'=>$autoOk,'configured'=>$cronConfigured,'recent'=>$recent,'last_run'=>$last,'cron'=>trim($cronText),'log_tail'=>$logTail],'job'=>$job,'message'=>$macOk&&$plansOk&&$blockOk&&$autoOk?'Patch Huawei aplicado: planos, MAC e bloqueio IPv6 validados e automáticos.':'Análise concluída. Existem itens pendentes ou a execução automática ainda não foi confirmada.'];
}
try{$action=$_SERVER['REQUEST_METHOD']==='POST'?(string)($_POST['action']??'status'):'status';if($action==='apply'){require_csrf((string)($_POST['csrf']??''));$d=db();$d->query("CREATE TABLE IF NOT EXISTS addon_huawei_patch_jobs(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,status VARCHAR(16) NOT NULL,requested_by VARCHAR(100) NOT NULL,requested_at DATETIME NOT NULL,finished_at DATETIME NULL,message TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$pending=$d->query("SELECT COUNT(*) FROM addon_huawei_patch_jobs WHERE status IN ('pending','running')")->fetch_row()[0];if((int)$pending>0)throw new RuntimeException('Já existe uma aplicação aguardando ou em execução.');$user=(string)($_SESSION['MKA_Usuario']??$_SESSION['MM_Usuario']??'MK-AUTH');$st=$d->prepare("INSERT INTO addon_huawei_patch_jobs(status,requested_by,requested_at,message) VALUES('pending',?,NOW(),'Solicitação confirmada no addon')");$st->bind_param('s',$user);$st->execute();$st->close();$d->close();$result=patch_snapshot();$result['queued']=true;$result['message']='Aplicação autorizada e colocada na fila segura. O executor iniciará em até 1 minuto.';json_response($result);}if($action!=='status')throw new RuntimeException('Ação inválida.');json_response(patch_snapshot());}catch(Throwable $e){json_response(['ok'=>false,'error'=>$e->getMessage()],422);}
