<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';require __DIR__.'/huawei_client.php';
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(['ok'=>false,'error'=>'Método não permitido.'],405);
function wizard_source_ip(string $target):string{$out=[];$code=1;exec('/sbin/ip route get '.escapeshellarg($target).' 2>/dev/null',$out,$code);$text=implode(' ',$out);return preg_match('/\bsrc\s+(\d+\.\d+\.\d+\.\d+)/',$text,$m)?$m[1]:'';}
function wizard_connection():array{$c=addon_config();$host=trim((string)($_POST['wizard_host']??''));$port=(int)($_POST['wizard_port']??22);$user=trim((string)($_POST['wizard_user']??''));$password=(string)($_POST['wizard_password']??'');if(!filter_var($host,FILTER_VALIDATE_IP))throw new RuntimeException('Informe o IP Huawei para esta análise.');if($port<1||$port>65535)throw new RuntimeException('Porta SSH temporária inválida.');if($user===''||strlen($user)>64||$password==='')throw new RuntimeException('Informe usuário e senha temporários do Huawei.');$c['ssh_host']=$host;$c['ssh_port']=$port;$c['ssh_user']=$user;$c['ssh_password']=$password;return$c;}
function wizard_values(array $c):array{$community=trim((string)($_POST['community']??''));$alias=trim((string)($_POST['alias']??'MKAUTH_ADDON'));if(!preg_match('/^[A-Za-z0-9_.-]{1,32}$/',$alias))throw new RuntimeException('Nome/alias inválido.');if(strlen($community)<8||!preg_match('/[A-Za-z]/',$community)||!preg_match('/[0-9]/',$community))throw new RuntimeException('A community deve ter ao menos 8 caracteres, letras e números.');$target=(string)($c['snmp_host']??$c['nas_ip']??$c['ssh_host']);$source=wizard_source_ip($target);if(!filter_var($source,FILTER_VALIDATE_IP))throw new RuntimeException('Não foi possível identificar o IP de origem do MK-AUTH.');return[$community,$alias,$source];}
try{
 require_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');$c=wizard_connection();
 if($action==='inventory'){$out=huawei_exec($c,"display version\ndisplay snmp-agent community\ndisplay current-configuration | include snmp-agent\ndisplay acl all");$source=wizard_source_ip((string)($c['snmp_host']??$c['nas_ip']??$c['ssh_host']));json_response(['ok'=>true,'source_ip'=>$source,'snmp_configured'=>stripos($out,'snmp-agent community')!==false,'acl_detected'=>stripos($out,'Basic ACL')!==false,'message'=>'Inventário concluído com credenciais temporárias. Nenhuma credencial foi salva.']);}
 [$community,$alias,$source]=wizard_values($c);$commands="system-view\nacl name MKAUTH-SNMP basic\n rule 5 permit source $source 0\n quit\nsnmp-agent\nsnmp-agent sys-info version v2c\nsnmp-agent community read cipher $community acl MKAUTH-SNMP alias $alias\ncommit\nreturn";
 if($action==='generate')json_response(['ok'=>true,'commands'=>$commands,'source_ip'=>$source,'message'=>'Configuração manual gerada.']);
 if($action!=='apply'||($_POST['confirm']??'')!=='APLICAR')throw new RuntimeException('Confirmação automática inválida.');$out=huawei_exec($c,$commands);if(preg_match('/Error:|Unrecognized command|Wrong parameter/i',$out))throw new RuntimeException('O Huawei recusou um comando. Use o modo manual e confira a versão do equipamento.');
 $dir=__DIR__.'/data';if(!is_dir($dir)||!is_writable($dir))throw new RuntimeException('SNMP configurado, mas a área privada do addon não permite salvar.');$saved=addon_config();$saved['snmp_community']=$community;$file=$dir.'/config.php';$tmp=$dir.'/config.php.tmp';$php="<?php\nreturn ".var_export($saved,true).";\n";if(file_put_contents($tmp,$php,LOCK_EX)===false||!rename($tmp,$file))throw new RuntimeException('SNMP configurado, mas não foi possível salvar a community no addon.');@chmod($file,0660);
 $snmp=[];$rc=1;exec('/usr/bin/snmpget -v2c -c '.escapeshellarg($community).' -t 3 -r 1 '.escapeshellarg((string)($saved['snmp_host']??$saved['nas_ip'])).' 1.3.6.1.2.1.1.3.0 2>&1',$snmp,$rc);json_response(['ok'=>$rc===0,'commands'=>$commands,'source_ip'=>$source,'message'=>$rc===0?'Configuração aplicada e SNMP validado.':'Comandos aplicados, mas o teste SNMP ainda não respondeu.','test_output'=>implode(' ',array_slice($snmp,-2))]);
}catch(Throwable $e){json_response(['ok'=>false,'error'=>$e->getMessage()],422);}
