<?php declare(strict_types=1);require __DIR__.'/bootstrap.php';$login=valid_login((string)($_GET['login']??''));?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tráfego Huawei</title>
<style>:root{font-family:Arial;color:#183246;background:#eaf1f5}*{box-sizing:border-box}body{margin:0;padding:28px}.top{max-width:1420px;margin:0 auto 18px;display:flex;justify-content:flex-end}.back{background:#17374a;color:#fff;padding:11px 17px;border-radius:9px;text-decoration:none;font-weight:bold}.layout{max-width:1420px;margin:auto;display:grid;grid-template-columns:360px 1fr;gap:28px}.card{background:#fff;border-radius:16px;padding:26px;box-shadow:0 8px 26px #17344c15}.profile{background:#193649;color:#fff}.kv{display:grid;grid-template-columns:125px 1fr;border-bottom:1px solid #ffffff20;padding:10px 0}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.btn{padding:11px 15px;border-radius:8px;text-decoration:none;background:#1371c8;color:#fff;font-weight:bold}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #dfe7ec;margin-bottom:18px}.live{background:#e7f7ed;color:#176c38;padding:8px 12px;border-radius:18px;font-weight:bold}.chart{width:100%;height:320px;background:#f5f8fa;border:1px solid #dbe5eb;border-radius:12px}.legend{font-size:18px;margin-top:14px;display:flex;gap:28px}.muted{color:#657482}.note{background:#fff4d6;color:#765600;padding:12px;border-radius:8px}@media(max-width:900px){.layout{grid-template-columns:1fr}body{padding:16px}}</style></head><body>
<div class="top"><a class="back" href="./">← SAIR DO MONITORAMENTO</a></div><div class="layout"><aside class="card profile"><small>MONITORAMENTO DO CLIENTE</small><h1 id="clientName"><?=htmlspecialchars($login)?></h1><div id="fields"></div><div class="actions"><a class="btn" href="/admin/addons/busca_inteligente/det_conn.php?login=<?=urlencode($login)?>">LOG DE CONEXÕES</a></div></aside>
<main class="card"><div class="head"><h2>Tráfego em tempo real</h2><span class="live">● SNMP Huawei</span></div><canvas id="chart" class="chart" width="1000" height="320"></canvas><div class="legend"><span>↓ Download <b id="down">0.00</b> Mbps</span><span>↑ Upload <b id="up">0.00</b> Mbps</span></div><p id="status" class="muted">Localizando o assinante na HUAWEI-AAA-MIB…</p><p class="note">O gráfico consulta diretamente, via SNMP, os contadores individuais de 64 bits do assinante no Huawei. Não usa RADIUS nem abre SSH.</p></main></div>
<script>
const login=<?=json_encode($login)?>,ctx=document.getElementById('chart').getContext('2d'),clientName=document.getElementById('clientName'),fields=document.getElementById('fields'),down=document.getElementById('down'),up=document.getElementById('up'),statusEl=document.getElementById('status');let prev=null,points=[],started=null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uptime=()=>{if(!started||isNaN(started))return'-';let n=Math.max(0,Math.floor((Date.now()-started.getTime())/1000)),d=Math.floor(n/86400);n%=86400;return(d?d+'d ':'')+String(Math.floor(n/3600)).padStart(2,'0')+'h '+String(Math.floor(n%3600/60)).padStart(2,'0')+'m'};
fetch('api_client.php?login='+encodeURIComponent(login)).then(r=>r.json()).then(j=>{if(!j.ok)throw Error(j.error);let c=j.client,q=j.qos||{},rate=n=>n?`${(Number(n)/1e6).toFixed(2)} Mbps`:'-';started=new Date(String(c.acctstarttime||'').replace(' ','T'));clientName.textContent=c.nome||c.username;let data=[['Login',c.username],['Status','Online'],['Contrato',c.contrato||'-'],['Conectado às',c.acctstarttime],['Uptime',uptime()],['IP',c.framedipaddress],['MAC',c.callingstationid],['Porta/VLAN',c.nasportid],['Plano',c.plano||'-'],['Ramal',c.ramal||'-']];fields.innerHTML=data.map(x=>`<div class="kv"><b>${esc(x[0])}</b><span data-key="${esc(x[0])}">${esc(x[1])}</span></div>`).join('');let box=document.getElementById('qosSummary');if(box){box.className='qos '+(q.ok?'qos-ok':'qos-bad');box.innerHTML=`<b>QoS ${q.ok?'correto':'divergente'}</b><span>↓ Download ${rate(q.output_bps)}</span><span>↑ Upload ${rate(q.input_bps)}</span><small>Validação dos atributos Huawei enviados pelo RADIUS para o plano ${esc(c.plano||'-')}.</small>`}setInterval(()=>{let u=fields.querySelector('[data-key="Uptime"]');if(u)u.textContent=uptime()},1000)}).catch(e=>statusEl.textContent=e.message);
function draw(hoverIndex=null){ctx.clearRect(0,0,1000,320);let max=Math.max(1,...points.flatMap(p=>[p.d,p.u])),den=Math.max(1,points.length-1),px=i=>25+i*950/den,py=v=>295-v/max*270;for(const[k,color]of[['d','#e75252'],['u','#2679c9']]){ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();points.forEach((p,i)=>{let x=px(i),y=py(p[k]);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}if(hoverIndex===null||!points[hoverIndex])return;let p=points[hoverIndex],x=px(hoverIndex),yd=py(p.d),yu=py(p.u);ctx.save();ctx.strokeStyle='#66788a';ctx.lineWidth=1;ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(x,18);ctx.lineTo(x,298);ctx.stroke();ctx.setLineDash([]);for(const[y,color]of[[yd,'#e75252'],[yu,'#2679c9']]){ctx.fillStyle='#fff';ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.stroke()}let lines=[p.time,'↓ Download  '+p.d.toFixed(2)+' Mbps','↑ Upload      '+p.u.toFixed(2)+' Mbps'],w=210,h=78,bx=Math.min(780,Math.max(8,x+14)),by=Math.max(8,Math.min(230,Math.min(yd,yu)-88));ctx.fillStyle='rgba(18,39,55,.94)';ctx.beginPath();ctx.roundRect?ctx.roundRect(bx,by,w,h,8):ctx.rect(bx,by,w,h);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 14px Arial';ctx.fillText(lines[0],bx+12,by+21);ctx.font='14px Arial';ctx.fillStyle='#ff8585';ctx.fillText(lines[1],bx+12,by+44);ctx.fillStyle='#75baff';ctx.fillText(lines[2],bx+12,by+65);ctx.restore()}
async function sample(){try{let r=await fetch('api_realtime.php?login='+encodeURIComponent(login)+'&_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha na consulta ao Huawei.');if(prev){let s=(j.sample_ms-prev.sample_ms)/1000,d=Math.max(0,(j.down_bytes-prev.down_bytes)*8/s/1e6),u=Math.max(0,(j.up_bytes-prev.up_bytes)*8/s/1e6);down.textContent=d.toFixed(2);up.textContent=u.toFixed(2);points.push({d,u,time:new Date(j.sample_ms).toLocaleTimeString()});if(points.length>30)points.shift();draw()}prev=j;statusEl.textContent=(j.interface||'Huawei')+' · '+(j.online_time||'')+' · atualizado '+new Date().toLocaleTimeString()}catch(e){statusEl.textContent='Monitoramento: '+e.message;clearInterval(timer)}}
document.getElementById('chart').addEventListener('mousemove',e=>{if(!points.length)return;let rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)*1000/rect.width,index=points.length===1?0:Math.round((x-25)/950*(points.length-1));draw(Math.max(0,Math.min(points.length-1,index)))});document.getElementById('chart').addEventListener('mouseleave',()=>draw());
let timer=setInterval(sample,3000);sample();addEventListener('beforeunload',()=>clearInterval(timer));
</script>
<script>
(function(){
 fetch('api_client.php?login='+encodeURIComponent(login)+'&validate='+Date.now(),{cache:'no-store'})
  .then(async r=>{let j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Cliente não está online no Huawei.')})
  .catch(e=>{if(timer)clearInterval(timer);document.querySelector('.layout').innerHTML='<main class="card" style="grid-column:1/-1;text-align:center"><h2>Cliente não conectado no Huawei</h2><p class="muted">'+esc(e.message)+'</p><p>Esta página mostra somente sessões cujo NAS-IP-Address corresponde ao Huawei configurado.</p><a class="btn" href="./">VOLTAR À LISTA</a></main>'});
})();
</script><style>.qos{display:flex;align-items:center;gap:18px;flex-wrap:wrap;margin:16px 0;padding:13px 15px;border-radius:10px}.qos-ok{background:#e7f7ed;color:#176c38}.qos-bad{background:#fdebec;color:#a9222d}.qos small{flex-basis:100%}</style><script>const qos=document.createElement('div');qos.id='qosSummary';qos.className='qos';qos.textContent='Validando QoS do plano…';document.querySelector('.legend').after(qos);</script></body></html>
