<?php declare(strict_types=1);require __DIR__.'/bootstrap.php';$user=(string)($_SESSION['MKA_Usuario']??'');$csrf=csrf_token();?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Huawei Online</title>
<style>:root{font-family:Arial;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.bar{height:62px;background:#101827;color:#fff;padding:0 24px;display:flex;align-items:center;justify-content:space-between}.bar-right,.actions,.row-actions{display:flex;align-items:center;gap:10px}.home,.btn,button{border:0;border-radius:8px;padding:10px 14px;text-decoration:none;cursor:pointer;background:#1167d8;color:#fff;font-weight:bold}.gear{font-size:18px;background:#34445d}.danger{background:#bd2732}.secondary{background:#e8eef8;color:#172033}button:disabled{opacity:.6;cursor:wait}main{padding:24px;max-width:1450px;margin:auto}.panel{background:#fff;border-radius:14px;padding:22px;box-shadow:0 4px 18px #16213a18}.subtitle{color:#687386;margin-top:-8px}.actions{flex-wrap:wrap;margin:16px 0}.search{padding:11px;width:320px;border:1px solid #ccd5df;border-radius:8px;margin-left:auto}.feedback{display:none;margin:12px 0;padding:12px 14px;border-radius:8px;font-weight:bold}.feedback.show{display:block}.feedback.info{background:#e8f1ff;color:#1559a6}.feedback.ok{background:#e7f7ed;color:#176c38}.feedback.error{background:#fdebec;color:#a9222d}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #e5eaf1;text-align:left}th{background:#edf3fb}.login{font-weight:bold;color:#075daf;text-decoration:none}.muted{color:#687386}.tablewrap{overflow:auto}.row-actions .btn,.row-actions button{padding:7px 10px;font-size:12px}.modal{position:fixed;inset:0;background:#0b1325aa;display:none;align-items:center;justify-content:center;padding:24px;z-index:20}.modal.open{display:flex}.modal-card{width:min(900px,96vw);max-height:92vh;background:#fff;border-radius:14px;overflow:auto;box-shadow:0 20px 60px #0008}.modal-card.wide{width:min(1250px,96vw);height:min(820px,92vh);display:flex;flex-direction:column;overflow:hidden}.modal-head{background:#101827;color:#fff;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}.modal-body{padding:20px}.close{background:#bd2732;padding:8px 13px}.modal iframe{border:0;width:100%;flex:1}.test-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.test-card{border:1px solid #dce4ed;border-radius:10px;padding:16px}.test-card.running{background:#fff8df}.test-card.ok{background:#e7f7ed;border-color:#9bd2ad}.test-card.error{background:#fdebec;border-color:#e5a8ad}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field label{display:block;font-weight:bold;margin-bottom:6px}.field input{width:100%;padding:11px;border:1px solid #bdc9d6;border-radius:8px}.full{grid-column:1/-1}.code{white-space:pre-wrap;background:#0c1524;color:#d9e8ff;border-radius:10px;padding:16px;max-height:330px;overflow:auto}.warning{background:#fff4d6;color:#765600;padding:12px;border-radius:8px}@media(max-width:900px){.test-grid,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.search{width:100%;margin-left:0}.bar-right span{display:none}}</style></head><body>
<header class="bar"><strong>Huawei Online</strong><div class="bar-right"><span>Usuário: <?=htmlspecialchars($user)?></span><button id="configBtn" class="gear" title="Configurações">⚙ CONFIGURAÇÕES</button><a class="home" href="/admin/addons/dashboard/">INÍCIO</a></div></header>
<main><section class="panel"><h2><span id="count">–</span> clientes Huawei online</h2><p class="subtitle">RADIUS lista sessões · SNMP verifica o equipamento · SSH coleta tráfego individual e desconecta clientes</p><div class="actions"><button id="wizardBtn">🪄 WIZARD</button><button id="refreshBtn">Atualizar sessões</button><button id="connectBtn">Testar conectividade</button><button id="userBtn" class="secondary">Criar usuário Huawei</button><button id="radiusBtn">Radius LOG</button><input id="filter" class="search" placeholder="Buscar nome, login, IP ou MAC"></div><div id="feedback" class="feedback info" role="status"></div><p id="status" class="muted">Carregando dados do RADIUS…</p><div class="tablewrap"><table><thead><tr><th>Cliente / Login</th><th>IP</th><th>MAC</th><th>Porta</th><th>Último update</th><th>Download</th><th>Upload</th><th>Ações</th></tr></thead><tbody id="rows"></tbody></table></div></section></main>

<div id="connectModal" class="modal"><div class="modal-card"><div class="modal-head"><strong>Teste completo de conectividade</strong><button class="close" data-close="connectModal">FECHAR</button></div><div class="modal-body"><div class="test-grid"><div id="testRadius" class="test-card"><b>RADIUS / banco</b><p>Aguardando teste.</p></div><div id="testSnmp" class="test-card"><b>SNMP Huawei</b><p>Aguardando teste.</p></div><div id="testSsh" class="test-card"><b>RADIUS CoA</b><p>Aguardando teste.</p></div></div><p class="muted">O CoA valida a comunicação administrativa na porta 3799 usando um login de teste inexistente. SSH permanece opcional para o Wizard.</p><button id="runTests">EXECUTAR TODOS OS TESTES</button></div></div></div>

<div id="configModal" class="modal"><div class="modal-card"><div class="modal-head"><strong>⚙ Configuração do Huawei</strong><button class="close" data-close="configModal">FECHAR</button></div><form id="configForm" class="modal-body"><div class="form-grid"><div class="field"><label>IP SNMP / gerência</label><input name="snmp_host" required placeholder="10.255.255.200"></div><div class="field"><label>Comunidade SNMP</label><input name="snmp_community" type="password" placeholder="Deixe vazio para manter"></div><div class="field"><label>IP SSH interno</label><input name="ssh_host" required placeholder="10.255.255.200"></div><div class="field"><label>Porta SSH</label><input name="ssh_port" type="number" min="1" max="65535" value="22" required></div><div class="field"><label>Usuário SSH dedicado</label><input name="ssh_user" required placeholder="mkauth-addon"></div><div class="field"><label>Senha SSH</label><input name="ssh_password" type="password" placeholder="Deixe vazio para manter"></div><div class="full warning">Use o IP interno alcançável pelo MK-AUTH. O usuário precisa de leitura para o gráfico; para o botão Desconectar, também precisa executar <code>cut access-user</code>.</div></div><div class="actions"><button type="submit">SALVAR CONFIGURAÇÕES</button><button type="button" id="configTest" class="secondary">SALVAR E TESTAR</button></div></form></div></div>

<div id="userModal" class="modal"><div class="modal-card"><div class="modal-head"><strong>Criar usuário dedicado no Huawei</strong><button class="close" data-close="userModal">FECHAR</button></div><div class="modal-body"><p class="warning">Este exemplo usa nível 3 porque a desconexão é um comando de gerenciamento. Restrinja o acesso SSH ao IP do MK-AUTH <b>172.31.200.5</b> conforme a política/ACL do seu Huawei e troque a senha gerada depois da instalação.</p><pre id="userCommand" class="code"></pre><div class="actions"><button id="copyUser">COPIAR COMANDOS</button><button id="newPassword" class="secondary">GERAR OUTRA SENHA</button></div><p class="muted">Depois de colar e executar no Huawei, use a engrenagem para salvar o mesmo usuário e senha no addon.</p></div></div></div>

<div id="wizardModal" class="modal"><div class="modal-card"><div class="modal-head"><strong>🪄 Wizard Huawei</strong><button class="close" data-close="wizardModal">FECHAR</button></div><div class="modal-body"><p>O Wizard verifica o equipamento antes de sugerir qualquer alteração. Communities cifradas não podem ser recuperadas; informe uma community conhecida ou crie uma nova dedicada.</p><div class="form-grid"><div class="field"><label>Nome/alias SNMP</label><input id="wizAlias" value="MKAUTH_ADDON" maxlength="32"></div><div class="field"><label>Community dedicada</label><input id="wizCommunity" type="password" placeholder="Mínimo 8 caracteres, letras e números"></div><div class="full warning">Modo automático altera a configuração do Huawei. Os comandos só serão enviados depois de você digitar <b>APLICAR</b>. O modo manual apenas gera o código para copiar.</div></div><div class="actions"><button id="wizInventory">1. ANALISAR HUAWEI</button><button id="wizManual" class="secondary">2. GERAR CONFIGURAÇÃO MANUAL</button><button id="wizAuto" class="danger">3. CONFIGURAR AUTOMATICAMENTE</button></div><pre id="wizReport" class="code">Aguardando início do Wizard.</pre><button id="copyWizard" class="secondary">COPIAR RELATÓRIO/COMANDOS</button></div></div></div>

<div id="radiusModal" class="modal"><div class="modal-card wide"><div class="modal-head"><strong>Radius LOG — eventos de autenticação</strong><button class="close" data-close="radiusModal">FECHAR</button></div><iframe id="radiusFrame" title="Logs do RADIUS" onload="cleanRadiusFrame()"></iframe></div></div>
<script>
const csrf=<?=json_encode($csrf)?>,el=id=>document.getElementById(id),count=el('count'),rows=el('rows'),statusEl=el('status'),feedback=el('feedback'),filter=el('filter'),refreshBtn=el('refreshBtn'),radiusFrame=el('radiusFrame');let sessions=[];filter.value='';const healthSummary=document.createElement('div');healthSummary.className='feedback show info';healthSummary.textContent='Verificando RADIUS, SNMP e SSH...';document.querySelector('.subtitle').after(healthSummary);
const fmt=n=>{n=Number(n||0);let u=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openModal(id){el(id).classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){el(id).classList.remove('open');if(id==='radiusModal')radiusFrame.src='about:blank';document.body.style.overflow=''}function notice(message,type='info'){feedback.textContent=message;feedback.className='feedback show '+type;clearTimeout(notice.timer);notice.timer=setTimeout(()=>feedback.className='feedback '+type,7000)}
function render(){let q=filter.value.toLowerCase(),list=sessions.filter(x=>[x.username,x.nome,x.framedipaddress,x.callingstationid].join(' ').toLowerCase().includes(q));rows.innerHTML=list.map(x=>`<tr><td><a class="login" href="detail.php?login=${encodeURIComponent(x.username)}">${esc(x.nome||x.username)}<br><small>${esc(x.username)}</small></a></td><td>${esc(x.framedipaddress)}</td><td>${esc(x.callingstationid)}</td><td>${esc(x.nasportid)}</td><td>${esc(x.acctupdatetime)}</td><td>${fmt(x.acctoutputoctets)}</td><td>${fmt(x.acctinputoctets)}</td><td><div class="row-actions"><a class="btn" href="detail.php?login=${encodeURIComponent(x.username)}">TRÁFEGO</a><button class="danger" onclick="disconnectClient('${esc(x.username)}')">DESCONECTAR</button></div></td></tr>`).join('')}
async function load(manual=false){refreshBtn.disabled=true;try{let r=await fetch('api_sessions.php?_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha ao consultar sessões.');sessions=j.sessions||[];count.textContent=j.count??sessions.length;render();let t=new Date().toLocaleTimeString();statusEl.textContent='Última atualização: '+t;if(manual)notice(`${sessions.length} sessões atualizadas às ${t}.`,'ok')}catch(e){notice(e.message,'error')}finally{refreshBtn.disabled=false}}
async function disconnectClient(login){if(!confirm(`Desconectar ${login} do Huawei agora? O cliente perderá a conexão PPPoE.`))return;let fd=new FormData();fd.append('csrf',csrf);fd.append('login',login);try{let r=await fetch('api_disconnect.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error);notice(j.message,'ok');setTimeout(()=>load(),1500)}catch(e){notice('Não foi possível desconectar: '+e.message,'error')}}
async function testCard(id,url){let card=el(id),p=card.querySelector('p');card.className='test-card running';p.textContent='Testando…';try{let r=await fetch(url+'?_='+Date.now(),{method:url==='api_sessions.php'?'GET':'POST',cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha no teste.');card.className='test-card ok';p.textContent=url==='api_sessions.php'?`${j.count??0} sessões Huawei encontradas no RADIUS.`:j.message;return true}catch(e){card.className='test-card error';p.textContent=e.message;return false}}
async function runTests(){el('runTests').disabled=true;let results=await Promise.all([testCard('testRadius','api_sessions.php'),testCard('testSnmp','api_health.php'),testCard('testSsh','api_coa_health.php')]);el('runTests').disabled=false;if(results.every(Boolean))notice('RADIUS, SNMP e CoA validados.','ok')}
async function loadConfig(first=false){let j=await fetch('api_config.php').then(r=>r.json()),c=j.config||{},f=el('configForm');f.snmp_host.value=c.snmp_host||'';f.ssh_host.value=c.ssh_host||'';f.ssh_port.value=c.ssh_port||22;f.ssh_user.value=c.ssh_user||'';f.snmp_community.placeholder=c.has_snmp_community?'Configurada — deixe vazio para manter':'Obrigatória';f.ssh_password.placeholder=c.has_ssh_password?'Configurada — deixe vazio para manter':'Obrigatória';if(first&&(!c.snmp_host||!c.ssh_host||!c.ssh_user||!c.has_snmp_community||!c.has_ssh_password))openModal('configModal')}
async function saveConfig(test=false){let fd=new FormData(el('configForm'));fd.append('csrf',csrf);let r=await fetch('api_config.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok){notice(j.error||'Falha ao salvar.','error');return}notice(j.message,'ok');closeModal('configModal');if(test){openModal('connectModal');runTests()}}
function generateUser(){let bytes=new Uint8Array(12);crypto.getRandomValues(bytes);let pass='MkA@'+Array.from(bytes,b=>(b%36).toString(36)).join('')+'#26';el('userCommand').textContent=`system-view\nssh user mkauth-addon\naaa\n local-user mkauth-addon password irreversible-cipher ${pass}\n local-user mkauth-addon service-type ssh\n local-user mkauth-addon level 3\n quit\nssh user mkauth-addon authentication-type password\nssh user mkauth-addon service-type stelnet\ncommit\nreturn`;let f=el('configForm');f.ssh_user.value='mkauth-addon';f.ssh_password.value=pass}
async function wizard(action,confirmWord=''){let fd=new FormData();fd.append('csrf',csrf);fd.append('action',action);fd.append('alias',el('wizAlias').value);fd.append('community',el('wizCommunity').value);fd.append('confirm',confirmWord);el('wizReport').textContent='Executando '+action+'…';try{let r=await fetch('api_wizard.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok&&action!=='apply')throw Error(j.error||'Falha no Wizard.');let report=`IP de origem MK-AUTH: ${j.source_ip||'-'}\nSNMP existente: ${j.snmp_configured?'sim':'não identificado'}\nACL identificada: ${j.acl_detected?'sim':'não identificado'}\nResultado: ${j.message||j.error||'-'}`;if(j.commands)report+='\n\nCOMANDOS UTILIZADOS:\n'+j.commands;if(j.test_output)report+='\n\nTESTE FINAL:\n'+j.test_output;el('wizReport').textContent=report;notice(j.message||'Wizard concluído.',j.ok?'ok':'error')}catch(e){el('wizReport').textContent='ERRO: '+e.message;notice(e.message,'error')}}
function cleanRadiusFrame(){if(!radiusFrame.src||radiusFrame.src==='about:blank')return;try{let d=radiusFrame.contentDocument,s=d.createElement('style');s.textContent=`html,body{margin:0!important;padding:0!important;background:#f4f7fb!important}body>*:not(main.radius-app){display:none!important}main.radius-app{display:block!important;margin:0!important;padding:16px!important;max-width:none!important}.radius-hero,.radius-summary,.radius-lines-form,.radius-nas-filter,.radius-actions,.radius-status-row{display:none!important}.radius-controls{margin:0 0 12px!important;padding:14px!important}.radius-control-row{display:block!important}.radius-toolbar{margin-top:12px!important;display:block!important}.radius-search{width:100%!important;max-width:none!important}.radius-log-panel{margin:0!important}.radius-log-list{max-height:none!important;height:auto!important}`;d.head.appendChild(s);let q=d.getElementById('radiusSearch');if(q)q.placeholder='Pesquisar eventos pelo login'}catch(e){notice('Modo compacto indisponível.','error')}}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));refreshBtn.onclick=()=>load(true);el('connectBtn').onclick=()=>{openModal('connectModal');runTests()};el('runTests').onclick=runTests;el('radiusBtn').onclick=()=>{radiusFrame.src='/admin/addons/radius/index.php?linhas=100';openModal('radiusModal')};el('configBtn').onclick=()=>{loadConfig();openModal('configModal')};el('userBtn').onclick=()=>{generateUser();openModal('userModal')};el('newPassword').onclick=generateUser;el('copyUser').onclick=async()=>{await navigator.clipboard.writeText(el('userCommand').textContent);notice('Comandos copiados.','ok')};el('wizardBtn').onclick=()=>openModal('wizardModal');el('wizInventory').onclick=()=>wizard('inventory');el('wizManual').onclick=()=>wizard('generate');el('wizAuto').onclick=()=>{let word=prompt('Esta ação alterará ACL e SNMP no Huawei. Digite APLICAR para confirmar:');if(word==='APLICAR')wizard('apply',word)};el('copyWizard').onclick=async()=>{await navigator.clipboard.writeText(el('wizReport').textContent);notice('Relatório copiado.','ok')};el('configForm').onsubmit=e=>{e.preventDefault();saveConfig(false)};el('configTest').onclick=()=>saveConfig(true);filter.oninput=render;loadConfig(true);load();
</script>
<script>
(function(){
 const grid=document.querySelector('#wizardModal .form-grid'),aliasField=el('wizAlias').closest('.field'),communityField=el('wizCommunity').closest('.field'),temporary=document.createElement('div');aliasField.style.display='none';communityField.querySelector('label').textContent='Community SNMP (senha de consulta)';temporary.className='full';temporary.innerHTML=`<h3>Acesso temporário para esta execução</h3><p class="muted">Usado somente para executar o Wizard. Em usuários com domínio Huawei use <b>&gt;</b>, por exemplo: bruno&gt;default_admin.</p><div class="form-grid"><div class="field"><label>IP Huawei</label><input id="wizHost" required placeholder="10.255.255.200"></div><div class="field"><label>Porta SSH</label><input id="wizPort" type="number" min="1" max="65535" value="22" required></div><div class="field"><label>Usuário administrador temporário</label><input id="wizUser" required placeholder="bruno&gt;default_admin"></div><div class="field"><label>Senha temporária</label><input id="wizPassword" type="password" required autocomplete="new-password"></div></div><h3>Usuário permanente exclusivo do addon</h3><p class="muted">Gerado aleatoriamente. O modo manual inclui os comandos para criá-lo; o modo automático cria e salva essas credenciais.</p><div class="form-grid"><div class="field"><label>Novo usuário SSH</label><input id="addonUser" readonly></div><div class="field"><label>Nova senha SSH</label><input id="addonPassword" readonly></div></div><button type="button" id="regenerateAddon" class="secondary">GERAR OUTRAS CREDENCIAIS</button>`;grid.prepend(temporary);
 async function wizardTemporary(action,confirmWord=''){let fd=new FormData();fd.append('csrf',csrf);fd.append('action',action);fd.append('alias',el('wizAlias').value);fd.append('community',el('wizCommunity').value);fd.append('confirm',confirmWord);fd.append('wizard_host',el('wizHost').value);fd.append('wizard_port',el('wizPort').value);fd.append('wizard_user',el('wizUser').value);fd.append('wizard_password',el('wizPassword').value);el('wizReport').textContent='Executando análise temporária...';try{let r=await fetch('api_wizard.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha no Wizard.');let report=`IP de origem MK-AUTH: ${j.source_ip||'-'}\nSNMP existente: ${j.snmp_configured?'sim':'não identificado'}\nACL identificada: ${j.acl_detected?'sim':'não identificado'}\nResultado: ${j.message||'-'}`;if(j.commands)report+='\n\nCOMANDOS UTILIZADOS:\n'+j.commands;if(j.test_output)report+='\n\nTESTE FINAL:\n'+j.test_output;el('wizReport').textContent=report;notice(j.message||'Wizard concluído.','ok')}catch(e){el('wizReport').textContent='ERRO: '+e.message;notice(e.message,'error')}}
 el('wizardBtn').onclick=async()=>{let j=await fetch('api_config.php?_='+Date.now()).then(r=>r.json()),c=j.config||{};el('wizHost').value=c.ssh_host||c.snmp_host||'';el('wizPort').value=c.ssh_port||22;el('wizUser').value=c.ssh_user||'';el('wizPassword').value='';openModal('wizardModal')};el('wizInventory').onclick=()=>wizardTemporary('inventory');el('wizManual').onclick=()=>wizardTemporary('generate');el('wizAuto').onclick=()=>{let word=prompt('Esta ação alterará ACL e SNMP no Huawei. Digite APLICAR para confirmar:');if(word==='APLICAR')wizardTemporary('apply',word)};
 async function refreshHealth(){let checks=await Promise.allSettled(['api_sessions.php','api_health.php','api_ssh_health.php'].map(async url=>{let r=await fetch(url+'?_='+Date.now(),{method:url==='api_sessions.php'?'GET':'POST',cache:'no-store'}),j=await r.json();return{ok:r.ok&&j.ok,error:j.error||''}}));let names=['RADIUS','SNMP','SSH'],parts=checks.map((x,i)=>x.status==='fulfilled'&&x.value.ok?`✅ ${names[i]}`:`❌ ${names[i]}: ${x.status==='fulfilled'?(x.value.error||'sem resposta'):'falha'}`),ok=checks.every(x=>x.status==='fulfilled'&&x.value.ok);healthSummary.className='feedback show '+(ok?'ok':'error');healthSummary.textContent=parts.join('  •  ')}
 radiusFrame.addEventListener('load',()=>{try{let d=radiusFrame.contentDocument,m=d&&d.querySelector('main.radius-app');if(m&&m.parentElement!==d.body){d.body.appendChild(m);cleanRadiusFrame()}}catch(e){notice('Não foi possível compactar o Radius LOG.','error')}});filter.value='';render();
})();
</script>
<script>
(function(){
 function newAddonCredentials(){let a=new Uint8Array(8);crypto.getRandomValues(a);let suffix=Array.from(a,b=>(b%36).toString(36)).join('');el('addonUser').value='mkauth-addon-'+suffix.slice(0,6);el('addonPassword').value='MkA@'+suffix+'Aa26#'}
 async function runWizardV3(action,confirmWord=''){let fd=new FormData();fd.append('csrf',csrf);fd.append('action',action);fd.append('community',el('wizCommunity').value);fd.append('confirm',confirmWord);fd.append('wizard_host',el('wizHost').value);fd.append('wizard_port',el('wizPort').value);fd.append('wizard_user',el('wizUser').value);fd.append('wizard_password',el('wizPassword').value);fd.append('addon_user',el('addonUser').value);fd.append('addon_password',el('addonPassword').value);el('wizReport').textContent=action==='inventory'?'Analisando communities, ACLs e conectividade SNMP...':'Preparando comandos completos...';try{let r=await fetch('api_wizard.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha no Wizard.');let report=`IP de origem MK-AUTH: ${j.source_ip||'-'}\nSNMP configurado: ${j.snmp_configured?'sim':'não identificado'}\nACL vinculada identificada: ${j.acl_detected?'sim':'não identificada'}\nResultado: ${j.message||'-'}`;if(j.recommendations&&j.recommendations.length)report+='\n\nDIAGNÓSTICO DETALHADO:\n- '+j.recommendations.join('\n- ');if(j.commands)report+=`\n\nNOVO USUÁRIO DO ADDON:\nUsuário: ${el('addonUser').value}\nSenha: ${el('addonPassword').value}\n\nCOMANDOS QUE SERÃO APLICADOS:\n${j.commands}`;if(j.test_output)report+='\n\nTESTE FINAL:\n'+j.test_output;el('wizReport').textContent=report;notice(j.message||'Wizard concluído.','ok');return j}catch(e){el('wizReport').textContent='ERRO: '+e.message;notice(e.message,'error');return null}}
 el('regenerateAddon').onclick=newAddonCredentials;el('wizardBtn').onclick=async()=>{let j=await fetch('api_config.php?_='+Date.now()).then(r=>r.json()),c=j.config||{};el('wizHost').value=c.ssh_host||c.snmp_host||'';el('wizPort').value=c.ssh_port||22;el('wizUser').value=c.ssh_user||'';el('wizPassword').value='';newAddonCredentials();openModal('wizardModal')};el('wizInventory').onclick=()=>runWizardV3('inventory');el('wizManual').onclick=()=>runWizardV3('generate');el('wizAuto').onclick=async()=>{let preview=await runWizardV3('generate');if(!preview)return;setTimeout(async()=>{let word=prompt('Os comandos acima serão aplicados no Huawei e criarão o usuário dedicado exibido. Digite APLICAR para confirmar:');if(word==='APLICAR')await runWizardV3('apply',word);else notice('Aplicação automática cancelada. Nenhum comando foi enviado.','info')},250)};
})();
</script>
<script>
(function(){
 const tableHead=document.querySelector('thead tr');tableHead.innerHTML='<th>Cliente / Login</th><th>IP</th><th>MAC</th><th>Porta / descrição</th><th>VLAN</th><th>Conectado às</th><th>Uptime</th><th>Último update</th><th>Ações</th>';
 const portFilter=document.createElement('select');portFilter.id='portFilter';portFilter.className='search';portFilter.style.marginLeft='0';portFilter.innerHTML='<option value="">Todas as portas/VLANs</option>';filter.before(portFilter);
 const parseDate=s=>{if(!s)return null;let d=new Date(String(s).replace(' ','T'));return isNaN(d)?null:d},duration=s=>{let d=parseDate(s);if(!d)return'-';let n=Math.max(0,Math.floor((Date.now()-d.getTime())/1000)),days=Math.floor(n/86400);n%=86400;let h=Math.floor(n/3600),m=Math.floor(n%3600/60);return(days?days+'d ':'')+String(h).padStart(2,'0')+'h '+String(m).padStart(2,'0')+'m'},vlanOf=p=>{let m=String(p||'').match(/(?:vlan|\.|-)(\d+)(?:\D*$)/i);return m?m[1]:'-'},dateTime=s=>{let d=parseDate(s);return d?d.toLocaleString('pt-BR'):(s||'-')};
 function updatePortFilter(){let current=portFilter.value,values=[...new Set(sessions.map(x=>x.nasportid).filter(Boolean))].sort();portFilter.innerHTML='<option value="">Todas as portas/VLANs</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}${vlanOf(v)!=='-'?' · VLAN '+vlanOf(v):''}</option>`).join('');portFilter.value=values.includes(current)?current:''}
 render=function(){updatePortFilter();let q=filter.value.trim().toLowerCase(),port=portFilter.value,list=sessions.filter(x=>(!port||x.nasportid===port)&&[x.username,x.nome,x.framedipaddress,x.callingstationid,x.nasportid,vlanOf(x.nasportid)].join(' ').toLowerCase().includes(q));rows.innerHTML=list.map(x=>`<tr><td><a class="login" href="detail.php?login=${encodeURIComponent(x.username)}">${esc(x.nome||x.username)}<br><small>${esc(x.username)}</small></a></td><td>${esc(x.framedipaddress)}</td><td>${esc(x.callingstationid)}</td><td>${esc(x.nasportid||'-')}</td><td>${esc(vlanOf(x.nasportid))}</td><td>${esc(dateTime(x.acctstarttime))}</td><td class="uptime" data-start="${esc(x.acctstarttime)}">${duration(x.acctstarttime)}</td><td>${esc(dateTime(x.acctupdatetime))}</td><td><div class="row-actions"><a class="btn" href="detail.php?login=${encodeURIComponent(x.username)}">TRÁFEGO</a><button class="danger" onclick="disconnectClient('${esc(x.username)}')">DESCONECTAR</button></div></td></tr>`).join('');if(!list.length)rows.innerHTML='<tr><td colspan="9" class="muted">Nenhuma sessão encontrada neste filtro.</td></tr>'};portFilter.onchange=render;
 const action=document.createElement('div');action.id='actionModal';action.className='modal';action.innerHTML='<div class="modal-card" style="max-width:620px"><div class="modal-head"><strong id="actionTitle">Confirmação</strong><button class="close" id="actionClose">FECHAR</button></div><div class="modal-body"><div id="actionMessage" class="test-card"></div><div class="actions"><button id="actionConfirm" class="danger">CONFIRMAR</button><button id="actionCancel" class="secondary">CANCELAR</button></div></div></div>';document.body.appendChild(action);let pending=null;const closeAction=()=>{action.classList.remove('open');pending=null;document.body.style.overflow=''};el('actionClose').onclick=closeAction;el('actionCancel').onclick=closeAction;el('actionConfirm').onclick=()=>{let fn=pending;if(fn)fn()};
 function actionState(title,message,type='info',confirmFn=null){el('actionTitle').textContent=title;let box=el('actionMessage');box.className='test-card '+(type==='ok'?'ok':type==='error'?'error':'running');box.textContent=message;pending=confirmFn;el('actionConfirm').style.display=confirmFn?'inline-flex':'none';el('actionCancel').style.display=type==='info'&&!confirmFn?'none':'inline-flex';el('actionCancel').textContent=confirmFn?'CANCELAR':'FECHAR';action.classList.add('open');document.body.style.overflow='hidden'}
 disconnectClient=login=>actionState('Confirmar desconexão',`Desconectar ${login} do Huawei agora? O cliente perderá a conexão PPPoE.`,'info',async()=>{pending=null;el('actionConfirm').style.display='none';el('actionCancel').style.display='none';actionState('Desconectando cliente',`Enviando comando ao Huawei para ${login}...`,'info');let fd=new FormData();fd.append('csrf',csrf);fd.append('login',login);try{let r=await fetch('api_disconnect.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Comando recusado.');actionState('Desconexão concluída',j.message,'ok');setTimeout(()=>load(true),1200)}catch(e){actionState('Falha na desconexão',e.message,'error')}});
 async function basicHealth(){let urls=['api_sessions.php','api_health.php','api_coa_health.php'],checks=await Promise.allSettled(urls.map(async(url,i)=>{let r=await fetch(url+'?_='+Date.now(),{method:i===0?'GET':'POST',cache:'no-store'}),j=await r.json();return{ok:r.ok&&j.ok,error:j.error||''}})),ok=i=>checks[i].status==='fulfilled'&&checks[i].value.ok;healthSummary.className='feedback show '+(ok(0)&&ok(1)&&ok(2)?'ok':'error');healthSummary.textContent=`${ok(0)?'✅':'❌'} RADIUS · ${ok(1)?'✅':'❌'} SNMP · ${ok(2)?'✅':'❌'} CoA 3799 · SSH opcional`}
 setInterval(()=>load(false),60000);setInterval(()=>document.querySelectorAll('.uptime').forEach(x=>x.textContent=duration(x.dataset.start)),1000);basicHealth();setTimeout(()=>render(),600);
})();
</script>
<script>
(function(){
 const form=el('configForm'),firstField=form.querySelector('.field');
 const field=document.createElement('div');field.className='field';field.innerHTML='<label>NAS-IP-Address do RADIUS</label><input name="nas_ip" required placeholder="10.31.10.2"><small class="muted">IP enviado pelo Huawei no atributo RADIUS NAS-IP-Address. Não é o IP de gerência.</small>';firstField.before(field);
 const originalLoadConfig=loadConfig;
 loadConfig=async function(first=false){await originalLoadConfig(false);let j=await fetch('api_config.php?_='+Date.now(),{cache:'no-store'}).then(r=>r.json()),c=j.config||{};form.nas_ip.value=c.nas_ip||'';if(first&&(!c.nas_ip||!c.snmp_host||!c.ssh_host||!c.ssh_user||!c.has_snmp_community||!c.has_ssh_password))openModal('configModal')};
 loadConfig(false);
})();
</script>
<script>
(function(){
 const analyze=document.createElement('button');analyze.id='patchAnalyzeBtn';analyze.textContent='PATCH PLANO E MAC';
 el('radiusBtn').after(analyze);
 const modal=document.createElement('div');modal.id='patchModal';modal.className='modal';modal.innerHTML=`<div class="modal-card"><div class="modal-head"><strong>Patch Huawei — Planos e MAC</strong><button class="close" id="patchClose">FECHAR</button></div><div class="modal-body"><p class="muted">A análise é somente leitura. A aplicação cria backup, instala a correção de MAC, sincroniza os atributos Huawei dos planos e ativa a execução automática a cada minuto.</p><div class="test-grid"><div id="patchMac" class="test-card"><b>Correção de MAC</b><p>Aguardando análise.</p></div><div id="patchPlans" class="test-card"><b>Planos Huawei</b><p>Aguardando análise.</p></div><div id="patchAuto" class="test-card"><b>Execução automática</b><p>Aguardando análise.</p></div></div><pre id="patchReport" class="code" style="margin-top:14px">Nenhuma alteração foi executada.</pre><div class="actions"><button id="patchRunAnalyze">ANALISAR NOVAMENTE</button><button id="patchRunApply" class="danger">APLICAR, CORRIGIR E ATIVAR</button></div></div></div>`;document.body.appendChild(modal);
 const cls=(node,ok)=>node.className='test-card '+(ok?'ok':'error');
 let patchData=null;
 function patchDetails(kind){if(!patchData)return;let j=patchData,text='';if(kind==='mac'){text='CORREÇÃO DE MAC\n\nTriggers encontrados:\n- '+(j.mac.triggers.length?j.mac.triggers.join('\n- '):'nenhum')+`\n\nINSERT: ${j.mac.insert===1?'OK':'PENDENTE'}\nUPDATE: ${j.mac.update===1?'OK':'PENDENTE'}\nConflitos: ${j.mac.conflicts}`;}else if(kind==='plans'){text=`PLANOS HUAWEI\n\nPlanos cadastrados: ${j.plans.total}\nHuawei-Input-Average-Rate: ${j.plans.input}/${j.plans.total}\nHuawei-Output-Average-Rate: ${j.plans.output}/${j.plans.total}\nPendentes: ${j.plans.mismatches}`;if(j.plans.pending.length){text+='\n\nDETALHES PENDENTES:';j.plans.pending.forEach(p=>{text+=`\n- ${p.nome}: esperado ${Number(p.velup||0)*1000}/${Number(p.veldown||0)*1000} bps; atual ${p.input_atual}/${p.output_atual}`})}else text+='\n\nTodos os planos estão sincronizados.';}else{text=`EXECUÇÃO AUTOMÁTICA\n\nCron instalada: ${j.automatic.configured?'SIM':'NÃO'}\nÚltima execução confirmada: ${j.automatic.last_run}\nExecução recente (até 3 min): ${j.automatic.recent?'SIM':'NÃO'}\n\nCRON:\n${j.automatic.cron||'não encontrada'}\n\nÚLTIMAS LINHAS DO LOG:\n${j.automatic.log_tail||'Sem erros registrados. Execuções bem-sucedidas são confirmadas pelo horário acima.'}`;}el('patchReport').textContent=text;}
 ['patchMac','patchPlans','patchAuto'].forEach((id,i)=>{let card=el(id);card.style.cursor='pointer';card.title='Clique para ver os detalhes';card.addEventListener('click',()=>patchDetails(['mac','plans','automatic'][i]));});
 function renderPatch(j){patchData=j;let mac=el('patchMac'),plans=el('patchPlans'),auto=el('patchAuto');cls(mac,j.mac.ok);cls(plans,j.plans.ok);cls(auto,j.automatic.ok);mac.querySelector('p').textContent=j.mac.ok?'Triggers de INSERT e UPDATE corretos; nenhum trigger conflitante.':`Triggers: insert ${j.mac.insert}, update ${j.mac.update}, conflitos ${j.mac.conflicts}.`;plans.querySelector('p').textContent=j.plans.ok?`${j.plans.total} planos sincronizados nos dois atributos Huawei.`:`${j.plans.mismatches} planos pendentes; input ${j.plans.input}/${j.plans.total}, output ${j.plans.output}/${j.plans.total}.`;auto.querySelector('p').textContent=j.automatic.ok?`Cron ativa e confirmada. Última execução: ${j.automatic.last_run}.`:j.automatic.configured?`Cron instalada, mas sem execução confirmada nos últimos 3 minutos. Última: ${j.automatic.last_run}.`:'Agendamento automático ainda não ativado.';let job=j.job?`\nÚltima solicitação #${j.job.id}: ${j.job.status} — ${j.job.message||''}`:'';el('patchReport').textContent=j.message+'\n\nClique em cada card para ver os detalhes.\n\nMAC: '+(j.mac.ok?'OK':'PENDENTE')+'\nPlanos: '+(j.plans.ok?'OK':'PENDENTE')+'\nAutomático: '+(j.automatic.ok?'ATIVO E CONFIRMADO':j.automatic.configured?'CONFIGURADO, SEM HEARTBEAT RECENTE':'INATIVO')+job;}
 async function patchStatus(){openModal('patchModal');el('patchReport').textContent='Analisando banco, triggers, atributos e agendamento...';try{let r=await fetch('api_patch.php?_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha na análise.');renderPatch(j)}catch(e){el('patchReport').textContent='ERRO: '+e.message;notice(e.message,'error')}}
 async function patchApply(){el('patchRunApply').disabled=true;el('patchReport').textContent='Registrando autorização na fila segura...';let fd=new FormData();fd.append('csrf',csrf);fd.append('action','apply');try{let r=await fetch('api_patch.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha na solicitação.');renderPatch(j);notice(j.message,'ok');let checks=0,poll=setInterval(async()=>{checks++;let x=await fetch('api_patch.php?_='+Date.now(),{cache:'no-store'}).then(r=>r.json());if(x.ok)renderPatch(x);if(!x.job||!['pending','running'].includes(x.job.status)||checks>=18){clearInterval(poll);el('patchRunApply').disabled=false}},5000)}catch(e){el('patchReport').textContent='ERRO: '+e.message;notice(e.message,'error');el('patchRunApply').disabled=false}}
 analyze.onclick=patchStatus;el('patchRunAnalyze').onclick=patchStatus;el('patchRunApply').onclick=patchApply;el('patchClose').onclick=()=>closeModal('patchModal');
})();
</script>
<style>.field select{width:100%;padding:11px;border:1px solid #bdc9d6;border-radius:8px;background:#fff}.snmp-v3[hidden],.snmp-community[hidden]{display:none!important}.qos-ok{color:#176c38;font-weight:bold}.qos-bad{color:#a9222d;font-weight:bold}</style>
<script>
(function(){
 document.querySelector('.subtitle').textContent='RADIUS lista sessões · SNMP coleta tráfego individual · CoA desconecta clientes · SSH opcional para o Wizard';
 const form=el('configForm'),snmpHost=form.elements.snmp_host,hostField=snmpHost.closest('.field');
 document.querySelector('#configForm .warning').innerHTML='O SSH é opcional e não é usado pelo gráfico. Configure-o somente para comandos administrativos, como <code>display access-user</code> e <code>cut access-user</code> (Desconectar).';
 const versionField=document.createElement('div');versionField.className='field';versionField.innerHTML='<label>Versão SNMP</label><select name="snmp_version"><option value="2c">SNMP v2c (recomendado)</option><option value="1">SNMP v1</option><option value="3">SNMP v3</option></select>';hostField.after(versionField);
 const community=form.elements.snmp_community.closest('.field');community.classList.add('snmp-community');
 const v3=document.createElement('div');v3.className='full snmp-v3';v3.innerHTML='<div class="form-grid"><div class="field"><label>Usuário SNMPv3</label><input name="snmp_v3_user"></div><div class="field"><label>Nível de segurança</label><select name="snmp_v3_level"><option value="authPriv">authPriv</option><option value="authNoPriv">authNoPriv</option><option value="noAuthNoPriv">noAuthNoPriv</option></select></div><div class="field v3-auth"><label>Autenticação</label><select name="snmp_v3_auth_protocol"><option>SHA</option><option>MD5</option></select></div><div class="field v3-auth"><label>Senha de autenticação</label><input name="snmp_v3_auth_password" type="password" placeholder="Deixe vazio para manter"></div><div class="field v3-priv"><label>Privacidade</label><select name="snmp_v3_priv_protocol"><option>AES</option><option>DES</option></select></div><div class="field v3-priv"><label>Senha de privacidade</label><input name="snmp_v3_priv_password" type="password" placeholder="Deixe vazio para manter"></div></div>';community.after(v3);
 const toggle=()=>{let is3=form.elements.snmp_version.value==='3',level=form.elements.snmp_v3_level.value;community.hidden=is3;v3.hidden=!is3;v3.querySelectorAll('.v3-auth').forEach(x=>x.hidden=!is3||level==='noAuthNoPriv');v3.querySelectorAll('.v3-priv').forEach(x=>x.hidden=!is3||level!=='authPriv')};form.elements.snmp_version.onchange=toggle;form.elements.snmp_v3_level.onchange=toggle;
 form.elements.ssh_host.required=false;form.elements.ssh_user.required=false;form.elements.ssh_password.required=false;
 const loadSnmp=async()=>{let j=await fetch('api_config.php?_='+Date.now(),{cache:'no-store'}).then(r=>r.json()),c=j.config||{};form.elements.snmp_version.value=c.snmp_version||'2c';form.elements.snmp_v3_user.value=c.snmp_v3_user||'';form.elements.snmp_v3_level.value=c.snmp_v3_level||'authPriv';form.elements.snmp_v3_auth_protocol.value=c.snmp_v3_auth_protocol||'SHA';form.elements.snmp_v3_priv_protocol.value=c.snmp_v3_priv_protocol||'AES';form.elements.snmp_v3_auth_password.placeholder=c.has_snmp_v3_auth_password?'Configurada — deixe vazio para manter':'Obrigatória conforme nível';form.elements.snmp_v3_priv_password.placeholder=c.has_snmp_v3_priv_password?'Configurada — deixe vazio para manter':'Obrigatória para authPriv';toggle()};loadSnmp();const previousLoad=loadConfig;loadConfig=async(first=false)=>{await previousLoad(first);await loadSnmp()};
 const head=document.querySelector('thead tr');head.innerHTML='<th>Cliente / Login</th><th>Plano</th><th>IP</th><th>MAC</th><th>Porta / descrição</th><th>VLAN</th><th>Conectado às</th><th>Uptime</th><th>Último update</th><th>Ações</th>';
 const parse=s=>{let d=s?new Date(String(s).replace(' ','T')):null;return d&&!isNaN(d)?d:null},dur=s=>{let d=parse(s);if(!d)return'-';let n=Math.max(0,Math.floor((Date.now()-d)/1000)),days=Math.floor(n/86400);n%=86400;return(days?days+'d ':'')+String(Math.floor(n/3600)).padStart(2,'0')+'h '+String(Math.floor(n%3600/60)).padStart(2,'0')+'m'},dt=s=>{let d=parse(s);return d?d.toLocaleString('pt-BR'):(s||'-')},vlan=p=>{let m=String(p||'').match(/(?:vlan|\.|-)(\d+)(?:\D*$)/i);return m?m[1]:'-'};
 render=function(){let pf=el('portFilter'),current=pf?pf.value:'',counts={};sessions.forEach(x=>{if(x.nasportid)counts[x.nasportid]=(counts[x.nasportid]||0)+1});let ports=Object.keys(counts).sort();if(pf){pf.innerHTML=`<option value="">Todas as portas/VLANs (${sessions.length} clientes)</option>`+ports.map(v=>`<option value="${esc(v)}">${esc(v)} (${counts[v]} ${counts[v]===1?'cliente':'clientes'})</option>`).join('');pf.value=ports.includes(current)?current:''}let q=filter.value.trim().toLowerCase(),list=sessions.filter(x=>(!pf||!pf.value||x.nasportid===pf.value)&&[x.username,x.nome,x.plano,x.framedipaddress,x.callingstationid,x.nasportid].join(' ').toLowerCase().includes(q));count.textContent=list.length;rows.innerHTML=list.map(x=>`<tr><td><a class="login" href="detail.php?login=${encodeURIComponent(x.username)}">${esc(x.nome||x.username)}<br><small>${esc(x.username)}</small></a></td><td><b>${esc(x.plano||'-')}</b></td><td>${esc(x.framedipaddress)}</td><td>${esc(x.callingstationid)}</td><td>${esc(x.nasportid||'-')}</td><td>${esc(vlan(x.nasportid))}</td><td>${esc(dt(x.acctstarttime))}</td><td class="uptime" data-start="${esc(x.acctstarttime)}">${dur(x.acctstarttime)}</td><td>${esc(dt(x.acctupdatetime))}</td><td><div class="row-actions"><a class="btn" href="detail.php?login=${encodeURIComponent(x.username)}">TRÁFEGO</a><button class="danger" onclick="disconnectClient('${esc(x.username)}')">DESCONECTAR</button></div></td></tr>`).join('');if(!list.length)rows.innerHTML='<tr><td colspan="10" class="muted">Nenhuma sessão encontrada neste filtro.</td></tr>'};filter.oninput=render;el('portFilter').onchange=render;setTimeout(render,300);
})();
</script>
<script>
(function(){
 const button=document.createElement('button');button.id='snmpSetupBtn';button.textContent='CONFIGURAR SNMP';el('userBtn').after(button);
 const modal=document.createElement('div');modal.id='snmpSetupModal';modal.className='modal';modal.innerHTML=`<div class="modal-card"><div class="modal-head"><strong>Configurar SNMP no Huawei</strong><button class="close" id="snmpSetupClose">FECHAR</button></div><div class="modal-body"><p class="muted">Gera os comandos Huawei e uma ACL exclusiva para permitir consultas somente a partir do MK-AUTH.</p><div class="form-grid"><div class="field"><label>Versão</label><select id="snmpSetupVersion"><option value="2c">SNMP v2c (recomendado)</option><option value="1">SNMP v1</option><option value="3">SNMP v3</option></select></div><div class="field"><label>ACL Huawei</label><input id="snmpSetupAcl" type="number" min="2000" max="3999" value="2998"></div><div class="field"><label>IP de origem do MK-AUTH</label><input id="snmpSetupSource" placeholder="Detectado automaticamente"></div><div class="field snmp-v12"><label>Community dedicada</label><input id="snmpSetupCommunity" type="password" placeholder="Mínimo 8 caracteres"></div><div class="field snmp-v3-create" hidden><label>Usuário SNMPv3</label><input id="snmpSetupV3User" value="mkauth_addon"></div><div class="field snmp-v3-create" hidden><label>Senha de autenticação SHA</label><input id="snmpSetupV3Auth" type="password"></div><div class="field snmp-v3-create" hidden><label>Senha de privacidade AES</label><input id="snmpSetupV3Priv" type="password"></div></div><div class="actions"><button id="snmpGenerate">GERAR COMANDOS</button><button id="snmpCopy" class="secondary">COPIAR COMANDOS</button></div><pre id="snmpCommands" class="code">Preencha os dados e clique em GERAR COMANDOS.</pre><p class="warning">A geração não altera o Huawei. Para aplicação automática com prévia e confirmação, use o WIZARD e uma credencial administrativa válida.</p></div></div>`;document.body.appendChild(modal);
 const version=el('snmpSetupVersion'),toggleCreate=()=>{let v3=version.value==='3';document.querySelectorAll('.snmp-v3-create').forEach(x=>x.hidden=!v3);document.querySelectorAll('.snmp-v12').forEach(x=>x.hidden=v3)};version.onchange=toggleCreate;
 button.onclick=()=>openModal('snmpSetupModal');el('snmpSetupClose').onclick=()=>closeModal('snmpSetupModal');
 el('snmpGenerate').onclick=async()=>{let fd=new FormData();fd.append('csrf',csrf);fd.append('version',version.value);fd.append('acl',el('snmpSetupAcl').value);fd.append('source_ip',el('snmpSetupSource').value);fd.append('community',el('snmpSetupCommunity').value);fd.append('v3_user',el('snmpSetupV3User').value);fd.append('v3_auth',el('snmpSetupV3Auth').value);fd.append('v3_priv',el('snmpSetupV3Priv').value);el('snmpCommands').textContent='Identificando a rota e gerando comandos...';try{let r=await fetch('api_snmp_template.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha ao gerar comandos.');el('snmpSetupSource').value=j.source_ip;el('snmpCommands').textContent=j.commands;notice(j.message,'ok')}catch(e){el('snmpCommands').textContent='ERRO: '+e.message;notice(e.message,'error')}};
 el('snmpCopy').onclick=async()=>{let text=el('snmpCommands').textContent;if(!text||text.startsWith('ERRO:')||text.startsWith('Preencha'))return notice('Gere os comandos primeiro.','error');await navigator.clipboard.writeText(text);notice('Comandos SNMP copiados.','ok')};
})();
</script></body></html>
