<?php declare(strict_types=1);require __DIR__.'/bootstrap.php';$user=(string)($_SESSION['MKA_Usuario']??'');?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Huawei Online</title>
<style>:root{font-family:Arial;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.bar{height:62px;background:#101827;color:#fff;padding:0 24px;display:flex;align-items:center;justify-content:space-between}.bar-right{display:flex;align-items:center;gap:20px}.home{color:#fff;text-decoration:none;background:#1d6ed2;padding:10px 16px;border-radius:8px;font-weight:bold}main{padding:24px;max-width:1450px;margin:auto}.panel{background:#fff;border-radius:14px;padding:22px;box-shadow:0 4px 18px #16213a18}.actions{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:16px 0}.btn,button{border:0;border-radius:8px;padding:11px 15px;text-decoration:none;cursor:pointer;background:#1167d8;color:#fff;font-weight:bold}.btn:disabled,button:disabled{opacity:.6;cursor:wait}.search{padding:11px;width:320px;border:1px solid #ccd5df;border-radius:8px;margin-left:auto}.feedback{display:none;margin:12px 0;padding:12px 14px;border-radius:8px;font-weight:bold}.feedback.show{display:block}.feedback.info{background:#e8f1ff;color:#1559a6}.feedback.ok{background:#e7f7ed;color:#176c38}.feedback.error{background:#fdebec;color:#a9222d}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #e5eaf1;text-align:left}th{background:#edf3fb}.login{font-weight:bold;color:#075daf;text-decoration:none}.muted{color:#687386}.tablewrap{overflow:auto}.modal{position:fixed;inset:0;background:#0b1325aa;display:none;align-items:center;justify-content:center;padding:24px;z-index:20}.modal.open{display:flex}.modal-card{width:min(1250px,96vw);height:min(820px,92vh);background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 20px 60px #0008;display:flex;flex-direction:column}.modal-head{background:#101827;color:#fff;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}.close{background:#bd2732;padding:8px 13px}.modal iframe{border:0;width:100%;flex:1}@media(max-width:800px){.search{width:100%;margin-left:0}.bar-right span{display:none}}</style></head><body>
<header class="bar"><strong>Huawei Online V2</strong><div class="bar-right"><span>Usuário: <?=htmlspecialchars($user)?></span><a class="home" href="/admin/addons/dashboard/">INÍCIO</a></div></header>
<main><section class="panel"><h2><span id="count">–</span> clientes Huawei online</h2><div class="actions"><button id="refreshBtn" type="button">Atualizar sessões</button><button id="snmpBtn" type="button">Testar SNMP</button><button id="radiusBtn" type="button">Radius LOG</button><input id="filter" class="search" placeholder="Buscar nome, login, IP ou MAC"></div><div id="feedback" class="feedback info" role="status"></div><p id="status" class="muted">Carregando dados do RADIUS…</p><div class="tablewrap"><table><thead><tr><th>Cliente / Login</th><th>IP</th><th>MAC</th><th>Porta</th><th>Início</th><th>Último update</th><th>Download</th><th>Upload</th></tr></thead><tbody id="rows"></tbody></table></div></section></main>
<div id="radiusModal" class="modal" role="dialog" aria-modal="true" aria-label="Radius LOG"><div class="modal-card"><div class="modal-head"><strong>Radius LOG</strong><button id="closeRadius" class="close" type="button">FECHAR</button></div><iframe id="radiusFrame" title="Logs do RADIUS"></iframe></div></div>
<script>
const el=id=>document.getElementById(id),count=el('count'),rows=el('rows'),statusEl=el('status'),feedback=el('feedback'),filter=el('filter'),refreshBtn=el('refreshBtn'),snmpBtn=el('snmpBtn'),radiusBtn=el('radiusBtn'),radiusModal=el('radiusModal'),radiusFrame=el('radiusFrame');let sessions=[];
const fmt=n=>{n=Number(n||0);let u=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,type='info'){feedback.textContent=message;feedback.className='feedback show '+type;clearTimeout(notice.timer);notice.timer=setTimeout(()=>feedback.className='feedback '+type,7000)}
function render(){let q=filter.value.toLowerCase(),list=sessions.filter(x=>[x.username,x.nome,x.framedipaddress,x.callingstationid].join(' ').toLowerCase().includes(q));rows.innerHTML=list.map(x=>`<tr><td><a class="login" href="detail.php?login=${encodeURIComponent(x.username)}">${esc(x.nome||x.username)}<br><small>${esc(x.username)}</small></a></td><td>${esc(x.framedipaddress)}</td><td>${esc(x.callingstationid)}</td><td>${esc(x.nasportid)}</td><td>${esc(x.acctstarttime)}</td><td>${esc(x.acctupdatetime)}</td><td>${fmt(x.acctoutputoctets)}</td><td>${fmt(x.acctinputoctets)}</td></tr>`).join('')}
async function load(manual=false){refreshBtn.disabled=true;refreshBtn.textContent='Atualizando…';try{let r=await fetch('api_sessions.php?_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha ao consultar sessões.');sessions=j.sessions||[];count.textContent=j.count??sessions.length;render();let time=new Date().toLocaleTimeString();statusEl.textContent='Última atualização: '+time+'.';if(manual)notice(`${sessions.length} sessões atualizadas às ${time}.`,'ok')}catch(e){statusEl.textContent='Não foi possível carregar as sessões.';notice(e.message,'error')}finally{refreshBtn.disabled=false;refreshBtn.textContent='Atualizar sessões'}}
async function testSnmp(){snmpBtn.disabled=true;snmpBtn.textContent='Testando…';notice('Consultando o Huawei via SNMP. Aguarde…','info');try{let r=await fetch('api_health.php?_='+Date.now(),{method:'POST',cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||j.message||'Huawei não respondeu ao SNMP.');notice(j.message,'ok')}catch(e){notice('Falha no teste SNMP: '+e.message,'error')}finally{snmpBtn.disabled=false;snmpBtn.textContent='Testar SNMP'}}
function openRadius(){radiusFrame.src='/admin/addons/radius/index.php';radiusModal.classList.add('open');document.body.style.overflow='hidden'}function closeRadius(){radiusModal.classList.remove('open');radiusFrame.src='about:blank';document.body.style.overflow=''}
refreshBtn.onclick=()=>load(true);snmpBtn.onclick=testSnmp;radiusBtn.onclick=openRadius;el('closeRadius').onclick=closeRadius;radiusModal.onclick=e=>{if(e.target===radiusModal)closeRadius()};document.onkeydown=e=>{if(e.key==='Escape')closeRadius()};filter.oninput=render;load();
</script></body></html>
